### ISSUE TITLE
ImportError: DLL load failed while importing shell

### ISSUE THREAD

**Issue by egeres** [tjguk/winshell#15]
Importing the library gives the following error:

```python
>>> import winshell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\winshell.py", line 32, in <module>
    from win32com.shell import shell, shellcon
ImportError: DLL load failed while importing shell: The specified procedure could not be found.
```

**Comment by john-hen** [comment]
I believe you need to have [pyWin32](https://pypi.org/project/pywin32) installed. WinShell does not explicitly declare it as a dependency, it seems, otherwise Pip would install it automatically.

**Comment by egeres** [comment]
Thank you for the advice! I have `pywin32` installed and it still doesn't work (as well as `pypiwin32`). Trying to import the library from a administrator shell doesn't work either. And I tried replacing `from win32com.shell import shell, shellcon` by `from win32comext.shell import shell, shellcon` as [said in this stackoverflow comment](https://github.com/mhammond/pywin32/issues/678#issuecomment-733941955) but that doesn't fix it

This is weird since it's running on other machine I have with windows with no issues so far 🤔

**Comment by egeres** [comment]
Apparently installing version 300 of pywin32 solves the issue on my machine! [This is the stackoverflow question that helped me](https://stackoverflow.com/a/62249872/5189462)
